FROM mediawiki:1.32.1
# Extensions build for 1.32
ADD extensions/BreadCrumbs2-REL1_32-gpk.tar.gz /var/www/html/extensions
ADD extensions/RSS-REL1_32-4a78159.tar.gz /var/www/html/extensions
ADD extensions/VisualEditor-REL1_32-e82e120.tar.gz /var/www/html/extensions
