FROM openjdk:8-jdk-alpine
RUN git config --global url.”https://a26659c4ceb5a53068f6248bb4f2e827dc4bc239:@github.com/".insteadOf “https://github.com/"
LABEL maintainer="grant.kohler@gmail.com"
VOLUME /tmp
EXPOSE 8080
